# PersistentVolumeClaims for Omada Controller
# Example setup for single-node MicroK8s cluster using local-path storage(CSI) storage.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs
  namespace: omada
  labels:
    app: omada-controller
spec:
  # storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi # Check official Omada docs and adjust acordingly

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
  namespace: omada
  labels:
    app: omada-controller
spec:
  # storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi # Check official Omada docs and adjust acordingly
